pipeline:
  name: UpdateExistingPipelineGithub
  identifier: UpdateExistingPipelineGithub
  projectIdentifier: ExistingPipeLineNdInputSet
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: Desc Added updated
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: HarnessApproval
                  name: Q1
                  identifier: Q1
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      userGroups: <+input>
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
        tags: {}
