pipeline:
  name: UpdateExistingPipelineTemplateGithub
  identifier: UpdateExistingPipelineTemplateGithub
  template:
    templateRef: usedPipelineInPipeline
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: q1
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: a1
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
  tags: {}
  projectIdentifier: ExistingPipeLineNdInputSet
  orgIdentifier: default
